# How much to drop at the start of the signal after recording [s].
drop_start = 11e-2
# How many different plaintext/key combinations to record.
num_points = 1

# Firmware configuration.
[fw]
# Channel.
channel = 20
# Modes use individual serial commands to trigger.
mode = "tinyaes"
# True to use a fixed key or False to vary it for each point.
fixed_key = false
# True to use a fixed plaintext or False to vary it for each point.
fixed_plaintext = false
# Fixed vs Fixed mode: alternate between two fixed p,k pairs which show large
# distance according to the leak model.
fixed_vs_fixed = false
# True to modulate data or False to use just the carrier.
modulate = false
# True to disable radio (conventional attack mode). Defaults at false
# for compatibility
conventional = true
# The sleep time between individual encryptions in slow mode collections.
slow_mode_sleep_time = 0.001

# SCAFF configuration.
[scaff.legacy]
sampling_rate = 10e6
num_traces_per_point = 125
num_traces_per_point_min = 100
# bandpass_lower = 2.30e6
# bandpass_upper = 2.40e6
bandpass_lower = 2.0e6
bandpass_upper = 2.2e6
lowpass_freq = 5e3
trigger_offset = 50e-6
trigger_rising = true
trigger_threshold = 0
signal_length = 200e-6
min_correlation = 5.5e-3

[scaff.io]
data_path = ""
data_pattern = "{}_iq.npy"
