[soapyrx]
# Sampling rate, in Hz.
sampling_rate = 10e6

[fw]
# Channel.
channel = 0
# Modes use individual serial commands to trigger.
mode = "tinyaes"
# True to use a fixed key or False to vary it for each point.
fixed_key = false
# True to use a fixed plaintext or False to vary it for each point.
fixed_plaintext = false
# Fixed vs Fixed mode: alternate between two fixed p,k pairs which show large
# distance according to the leak model.
fixed_vs_fixed = false
# True to modulate data or False to use just the carrier.
modulate = false
# True to disable radio (conventional attack mode). Defaults at false
# for compatibility
conventional = true
# The sleep time between individual encryptions in slow mode collections.
slow_mode_sleep_time = 0.001
# How many different plaintext/key combinations to record.
num_points = 1
# How many traces executed by the firmware.
num_traces_per_point = 500
# How many traces to keep from the recording.
num_traces_per_point_min = 300

[scaff]
# Lower cut-off frequency of the band-pass filter.
bandpass_lower = 1.97e6
# Upper cut-off frequency of the band-pass filter.
bandpass_upper = 2.15e6
# Cut-off frequency of the low-pass filter.
lowpass_freq = 5e3
# How much to drop at the start of the trace, in seconds.
drop_start = 50e-3
# How much to include before the trigger, in seconds.
trigger_offset = 100e-6
# True for triggering on a rising edge, False otherwise.
trigger_rising = true
# Threshold used for triggering instead of average.
trigger_threshold = 0
# Length of the signal portion to keep, in seconds, starting at
# trigger - trigger_offset.
signal_length = 300e-6
# Name of the template to load, or None.
template_name = ""
# Traces with a lower correlation will be discarded.
min_correlation = 0.00
# Keep all raw
keep_all = false
